FROM node:10.13.0

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

COPY . ./
RUN npm install

RUN npm install -g ionic
RUN npm install -g @angular/cli@latest

EXPOSE 8100

CMD ionic serve --address 0.0.0.0